module_name: "steering_wheel_module_24"


buckets:
    bucket_1:
        frequency_hz: 250
        parameters:
            swButon0_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon1_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon2_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon3_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon4_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swButon5_state:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swDial_a_ul:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
            swDial_b_ul:
              ADC: NON_ADC
              sensor: NON_ADC
              samples_buffered: 1
